runtime: nodejs
vm: true
api_version: 1

# Temporary workaround to allow access to Google Cloud Datastore
beta_settings:
  service_account_scopes: >
    https://www.googleapis.com/auth/userinfo.email,
    https://www.googleapis.com/auth/cloud-platform
env_variables:
  OAUTH2_CALLBACK: https://home-cloud-server.appspot.com/oauth2callback

# Temporary workaround for a Cloud SDK bug.
# Ensures that node_modules directory and any .log files are not uploaded (the
# other entries are the default values for skip_files). This will skip any Unix
# hidden files (such as the .git directory)
skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - ^(.*/)?.*/node_modules/.*$
 - ^(.*/)?.*\.log$